Repository membraneframework/membrane_rtc_engine, pull requests merged in 2021-12, with the labels that each got.

#53 Disable integrated turn by default
  lib/membrane_rtc_engine/engine.ex
  mix.exs
Labels: bug

#47 Modular rtc engine
  assets/js/mediaEvent.ts
  assets/js/membraneWebRTC.ts
  lib/membrane_rtc_engine/endpoint.ex
  lib/membrane_rtc_engine/endpoints/hls_endpoint.ex
  lib/membrane_rtc_engine/endpoints/webrtc_endpoint.ex
  lib/membrane_rtc_engine/engine.ex
  lib/membrane_rtc_engine/media_event.ex
  lib/membrane_rtc_engine/peer.ex
  lib/membrane_rtc_engine/track.ex
  mix.exs
  mix.lock
  test/membrane_rtc_engine/rtc_test.exs
Labels: enhancement

#62 Improve docs and make API more consistent
  assets/js/membraneWebRTC.ts
  lib/membrane_rtc_engine/endpoint.ex
  lib/membrane_rtc_engine/endpoints/hls_endpoint.ex
  lib/membrane_rtc_engine/endpoints/webrtc_endpoint.ex
  lib/membrane_rtc_engine/engine.ex
  lib/membrane_rtc_engine/media_event.ex
  lib/membrane_rtc_engine/message.ex
  lib/membrane_rtc_engine/peer.ex
  lib/membrane_rtc_engine/utils.ex
  mix.exs
  test/membrane_rtc_engine/media_event_test.exs
  test/membrane_rtc_engine/rtc_test.exs
Labels: bug, documentation, api
