Repository membraneframework/membrane_rtc_engine, pull requests merged in 2022-01, with the labels that each got.

#69 Fix `add_peer` function and `Membrane.RTC.Engine.Message.t()`
  lib/membrane_rtc_engine/engine.ex
  lib/membrane_rtc_engine/message.ex
  test/membrane_rtc_engine/rtc_test.exs
Labels: bug, api

#73 Support hls mode selection
  lib/membrane_rtc_engine/endpoints/hls_endpoint.ex
  mix.exs
  mix.lock
Labels: enhancement

#75 Implement TLS TURN
  assets/js/membraneWebRTC.ts
  lib/membrane_rtc_engine/endpoints/webrtc_endpoint.ex
Labels: enhancement

#76 Hls fixes
  lib/membrane_rtc_engine/endpoints/hls_endpoint.ex
  lib/membrane_rtc_engine/endpoints/webrtc_endpoint.ex
  lib/membrane_rtc_engine/engine.ex
  lib/membrane_rtc_engine/utils.ex
  mix.exs
  mix.lock
Labels: bug
